#!/bin/bash -e

DOCKER_REPO=${DOCKER_REPO}
NAMESPACE=${NAMESPACE:-namely}
GRPC_VERSION=${GRPC_VERSION:-1.27}
GRPC_JAVA_VERSION=${GRPC_JAVA_VERSION:-1.27}
PROTOC_VERSION=${PROTOC_VERSION:-3.11.2}
BUILD_VERSION=${BUILD_VERSION:-0}
CONTAINER=${DOCKER_REPO}${NAMESPACE}
LATEST=${1:false}
BUILDS=("protoc-all" "protoc-swift" "protoc" "prototool" "grpc-cli" "gen-grpc-gateway")
